all: ptrace1 ptrace2 ptrace3

ptrace1:
	clang ptrace1.m -o ptrace1

ptrace2:
	clang ptrace2.m -o ptrace2

ptrace3:
	clang ptrace3.m -o ptrace3 -arch x86_64

ptrace3arm:
	clang ptrace3.m -o ptrace3

clean:
	rm -rf ptrace1 ptrace2 ptrace3